import type { Draft } from './session-form';
import type { CreateController } from './use-create-session';
import { FormField } from './FormField';
import { localStart, timezone } from './date-time';
export function CreateSession({ form }: {
    form: CreateController;
}) {
    const { draft, errors, change, pending, coaches } = form;
    const props = (key: keyof Draft, hint?: string) => ({ id: key, name: key, value: draft[key], disabled: pending, 'aria-invalid': errors[key] ? true as const : undefined, 'aria-describedby': [hint ? `${key}-hint` : '', errors[key] ? `${key}-error` : ''].filter(Boolean).join(' ') || undefined, onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => change(key, e.target.value) });
    const field = (key: keyof Draft, label: string, type = 'text', hint?: string) => <FormField name={key} label={label} hint={hint} error={errors[key]}><input {...props(key, hint)} type={type} autoComplete="off" required={key !== 'description' && key !== 'trainerNotes'} step={type === 'number' ? 1 : undefined}/></FormField>;
    const start = localStart(draft.date, draft.time);
    const blocked = coaches.kind !== 'success' || !coaches.data.data.length;
    return <section className="create-view"><a className="back-link" href="#/sessions">← Back to sessions</a><h1 tabIndex={-1} id="create-heading">Create session</h1><p className="muted">Times are in your local timezone: {timezone()}. All fields are required unless marked optional.</p>
  <form className="surface create-form" noValidate aria-busy={pending} onSubmit={event => { event.preventDefault(); void form.submit(); }}>
    {form.message ? <div id="form-error" className="error-banner" tabIndex={-1} role="alert">{form.message}<p><a href="#/sessions">Check sessions</a></p></div> : null}
    <fieldset><legend>Session</legend>{field('title', 'Title', 'text', '3–80 characters.')}<FormField name="type" label="Session type" error={errors.type}><select {...props('type')} required><option value="">Select type</option><option value="training">Training</option><option value="camp">Camp</option><option value="private">Private</option></select></FormField></fieldset>
    <fieldset><legend>Schedule</legend><div className="form-grid">{field('date', 'Date', 'date')}{field('time', 'Start time', 'time')}</div>{start?.ambiguous ? <p role="status">This time occurs twice; the earlier occurrence will be used: {new Intl.DateTimeFormat(undefined, { timeZoneName: 'shortOffset', hour: 'numeric', minute: 'numeric' }).format(new Date(start.iso))}.</p> : null}<div className="form-grid">{field('duration', 'Duration (minutes)', 'number', '30–240 minutes.')}<FormField name="coachId" label="Coach" error={errors.coachId}><select {...props('coachId')} disabled={pending || blocked} required aria-describedby={blocked ? 'coach-feedback' : errors.coachId ? 'coachId-error' : undefined}><option value="">Select coach</option>{coaches.kind === 'success' ? coaches.data.data.map(c => <option key={c.id} value={c.id}>{c.name}</option>) : null}</select></FormField></div>{blocked ? <div id="coach-feedback" role="status">{coaches.kind === 'loading' ? 'Loading coaches…' : coaches.kind === 'error' ? 'Coaches couldn’t load. Retry to choose a coach.' : 'No coaches are available.'}{coaches.kind !== 'loading' ? <button type="button" onClick={form.retryCoaches}>Retry coaches</button> : null}</div> : null}</fieldset>
    <fieldset><legend>Location and capacity</legend>{field('locationName', 'Location name', 'text', '2–80 characters.')}{field('locationAddress', 'Location address', 'text', '3–120 characters.')}{field('capacity', 'Capacity', 'number', '1–100 places.')}</fieldset>
    <fieldset aria-describedby={errors.visibility ? 'visibility-error' : undefined}><legend>Visibility</legend><div className="radio-group">{(['public', 'invite-only'] as const).map(v => <label key={v}><input type="radio" name="visibility" aria-invalid={errors.visibility ? true : undefined} aria-describedby={errors.visibility ? 'visibility-error' : undefined} value={v} checked={draft.visibility === v} disabled={pending} onChange={() => change('visibility', v)}/>{v === 'public' ? 'Public' : 'Invite-only'}</label>)}</div>{errors.visibility ? <span className="field-error" id="visibility-error">{errors.visibility}</span> : null}</fieldset>
    <fieldset><legend>Optional details</legend>{(['description', 'trainerNotes'] as const).map(key => <FormField key={key} name={key} label={key === 'description' ? 'Description (optional)' : 'Trainer notes (optional)'} hint={key === 'trainerNotes' ? `${draft.trainerNotes.length} / 500 characters` : undefined} error={errors[key]}><textarea {...props(key, key === 'trainerNotes' ? 'count' : undefined)} rows={4}/></FormField>)}</fieldset>
    <div className="form-actions"><button className="primary" type="submit" disabled={pending || blocked} aria-describedby={blocked ? 'coach-feedback' : undefined}>{pending ? 'Creating session…' : 'Create session'}</button><a href="#/sessions">Back to sessions</a></div><p role="status">{pending ? 'Creating session…' : ''}</p>
  </form></section>;
}
